var annotated_dup =
[
    [ "std", "namespacestd.html", [
      [ "iterator_traits< zisa::HalfRadii::Iterator >", "structstd_1_1iterator__traits_3_01zisa_1_1HalfRadii_1_1Iterator_01_4.html", "structstd_1_1iterator__traits_3_01zisa_1_1HalfRadii_1_1Iterator_01_4" ],
      [ "tuple_element< i, zisa::Cartesian< n > >", "structstd_1_1tuple__element_3_01i_00_01zisa_1_1Cartesian_3_01n_01_4_01_4.html", "structstd_1_1tuple__element_3_01i_00_01zisa_1_1Cartesian_3_01n_01_4_01_4" ],
      [ "tuple_element< i, zisa::XYZ >", "structstd_1_1tuple__element_3_01i_00_01zisa_1_1XYZ_01_4.html", "structstd_1_1tuple__element_3_01i_00_01zisa_1_1XYZ_01_4" ],
      [ "tuple_size< zisa::Cartesian< n > >", "structstd_1_1tuple__size_3_01zisa_1_1Cartesian_3_01n_01_4_01_4.html", null ],
      [ "tuple_size< zisa::XYZ >", "structstd_1_1tuple__size_3_01zisa_1_1XYZ_01_4.html", null ]
    ] ],
    [ "zisa", "namespacezisa.html", [
      [ "detail", "namespacezisa_1_1detail.html", [
        [ "LMDRhoEBar", "classzisa_1_1detail_1_1LMDRhoEBar.html", "classzisa_1_1detail_1_1LMDRhoEBar" ],
        [ "MakeEquilibrium", "classzisa_1_1detail_1_1MakeEquilibrium.html", null ],
        [ "MakeEquilibrium< IsentropicEquilibrium< EOS, Gravity > >", "classzisa_1_1detail_1_1MakeEquilibrium_3_01IsentropicEquilibrium_3_01EOS_00_01Gravity_01_4_01_4.html", null ],
        [ "MakeEquilibrium< NoEquilibrium >", "classzisa_1_1detail_1_1MakeEquilibrium_3_01NoEquilibrium_01_4.html", null ],
        [ "UnitDomain", "structzisa_1_1detail_1_1UnitDomain.html", null ]
      ] ],
      [ "opengl", "namespacezisa_1_1opengl.html", [
        [ "Window", "classzisa_1_1opengl_1_1Window.html", "classzisa_1_1opengl_1_1Window" ]
      ] ],
      [ "reduce", "namespacezisa_1_1reduce.html", [
        [ "detail", "namespacezisa_1_1reduce_1_1detail.html", [
          [ "return_type_trait", "structzisa_1_1reduce_1_1detail_1_1return__type__trait.html", null ],
          [ "return_type_trait< Range, Transform, false >", "structzisa_1_1reduce_1_1detail_1_1return__type__trait_3_01Range_00_01Transform_00_01false_01_4.html", "structzisa_1_1reduce_1_1detail_1_1return__type__trait_3_01Range_00_01Transform_00_01false_01_4" ],
          [ "return_type_trait< Range, Transform, true >", "structzisa_1_1reduce_1_1detail_1_1return__type__trait_3_01Range_00_01Transform_00_01true_01_4.html", "structzisa_1_1reduce_1_1detail_1_1return__type__trait_3_01Range_00_01Transform_00_01true_01_4" ]
        ] ]
      ] ],
      [ "AllReduce", "classzisa_1_1AllReduce.html", "classzisa_1_1AllReduce" ],
      [ "AllVariables", "classzisa_1_1AllVariables.html", "classzisa_1_1AllVariables" ],
      [ "AllVariablesDimensions", "structzisa_1_1AllVariablesDimensions.html", "structzisa_1_1AllVariablesDimensions" ],
      [ "AllVariablesGatherer", "classzisa_1_1AllVariablesGatherer.html", "classzisa_1_1AllVariablesGatherer" ],
      [ "AllVariablesScatterer", "classzisa_1_1AllVariablesScatterer.html", "classzisa_1_1AllVariablesScatterer" ],
      [ "array_save_traits< CellFlags >", "structzisa_1_1array__save__traits_3_01CellFlags_01_4.html", "structzisa_1_1array__save__traits_3_01CellFlags_01_4" ],
      [ "array_save_traits< StencilFamily >", "structzisa_1_1array__save__traits_3_01StencilFamily_01_4.html", "structzisa_1_1array__save__traits_3_01StencilFamily_01_4" ],
      [ "array_save_traits< XYZ >", "structzisa_1_1array__save__traits_3_01XYZ_01_4.html", "structzisa_1_1array__save__traits_3_01XYZ_01_4" ],
      [ "ArrayGatherer", "classzisa_1_1ArrayGatherer.html", "classzisa_1_1ArrayGatherer" ],
      [ "ArrayScatterer", "classzisa_1_1ArrayScatterer.html", "classzisa_1_1ArrayScatterer" ],
      [ "AxialAlignment", "classzisa_1_1AxialAlignment.html", "classzisa_1_1AxialAlignment" ],
      [ "Ball", "classzisa_1_1Ball.html", "classzisa_1_1Ball" ],
      [ "Barycentric2D", "classzisa_1_1Barycentric2D.html", "classzisa_1_1Barycentric2D" ],
      [ "Barycentric3D", "classzisa_1_1Barycentric3D.html", "classzisa_1_1Barycentric3D" ],
      [ "BoundaryCondition", "classzisa_1_1BoundaryCondition.html", "classzisa_1_1BoundaryCondition" ],
      [ "BoundingBox", "structzisa_1_1BoundingBox.html", "structzisa_1_1BoundingBox" ],
      [ "ButcherTableau", "structzisa_1_1ButcherTableau.html", "structzisa_1_1ButcherTableau" ],
      [ "CachedLocalReconstruction", "classzisa_1_1CachedLocalReconstruction.html", "classzisa_1_1CachedLocalReconstruction" ],
      [ "Cartesian", "classzisa_1_1Cartesian.html", "classzisa_1_1Cartesian" ],
      [ "CartesianAbs", "classzisa_1_1CartesianAbs.html", "classzisa_1_1CartesianAbs" ],
      [ "CartesianAnd", "classzisa_1_1CartesianAnd.html", "classzisa_1_1CartesianAnd" ],
      [ "CartesianCross", "classzisa_1_1CartesianCross.html", "classzisa_1_1CartesianCross" ],
      [ "CartesianDivision", "classzisa_1_1CartesianDivision.html", "classzisa_1_1CartesianDivision" ],
      [ "CartesianEqual", "classzisa_1_1CartesianEqual.html", "classzisa_1_1CartesianEqual" ],
      [ "CartesianExpr", "classzisa_1_1CartesianExpr.html", "classzisa_1_1CartesianExpr" ],
      [ "CartesianLess", "classzisa_1_1CartesianLess.html", "classzisa_1_1CartesianLess" ],
      [ "CartesianLessEqual", "classzisa_1_1CartesianLessEqual.html", "classzisa_1_1CartesianLessEqual" ],
      [ "CartesianLog", "classzisa_1_1CartesianLog.html", "classzisa_1_1CartesianLog" ],
      [ "CartesianLogic", "classzisa_1_1CartesianLogic.html", null ],
      [ "CartesianMinus", "classzisa_1_1CartesianMinus.html", "classzisa_1_1CartesianMinus" ],
      [ "CartesianNot", "classzisa_1_1CartesianNot.html", "classzisa_1_1CartesianNot" ],
      [ "CartesianNotEqual", "classzisa_1_1CartesianNotEqual.html", "classzisa_1_1CartesianNotEqual" ],
      [ "CartesianOr", "classzisa_1_1CartesianOr.html", "classzisa_1_1CartesianOr" ],
      [ "CartesianPlus", "classzisa_1_1CartesianPlus.html", "classzisa_1_1CartesianPlus" ],
      [ "CartesianPlusScalar", "classzisa_1_1CartesianPlusScalar.html", "classzisa_1_1CartesianPlusScalar" ],
      [ "CartesianProduct", "classzisa_1_1CartesianProduct.html", "classzisa_1_1CartesianProduct" ],
      [ "CartesianScale", "classzisa_1_1CartesianScale.html", "classzisa_1_1CartesianScale" ],
      [ "Cell", "classzisa_1_1Cell.html", "classzisa_1_1Cell" ],
      [ "cell_flags_dispatch_tag", "structzisa_1_1cell__flags__dispatch__tag.html", null ],
      [ "CellFlags", "structzisa_1_1CellFlags.html", "structzisa_1_1CellFlags" ],
      [ "CellRange", "classzisa_1_1CellRange.html", "classzisa_1_1CellRange" ],
      [ "CFLCondition", "classzisa_1_1CFLCondition.html", "classzisa_1_1CFLCondition" ],
      [ "ColorMap", "classzisa_1_1ColorMap.html", "classzisa_1_1ColorMap" ],
      [ "ConstantGravity", "classzisa_1_1ConstantGravity.html", "classzisa_1_1ConstantGravity" ],
      [ "ConstantGravityAxial", "classzisa_1_1ConstantGravityAxial.html", null ],
      [ "ConstantGravityRadial", "classzisa_1_1ConstantGravityRadial.html", "classzisa_1_1ConstantGravityRadial" ],
      [ "CVarConstExpr", "classzisa_1_1CVarConstExpr.html", "classzisa_1_1CVarConstExpr" ],
      [ "CVarExpr", "classzisa_1_1CVarExpr.html", "classzisa_1_1CVarExpr" ],
      [ "CWENO_AO", "classzisa_1_1CWENO__AO.html", "classzisa_1_1CWENO__AO" ],
      [ "Cycle", "structzisa_1_1Cycle.html", "structzisa_1_1Cycle" ],
      [ "DataSource", "classzisa_1_1DataSource.html", "classzisa_1_1DataSource" ],
      [ "DenormalizedRule", "structzisa_1_1DenormalizedRule.html", "structzisa_1_1DenormalizedRule" ],
      [ "DereferenceConstGridVariables", "classzisa_1_1DereferenceConstGridVariables.html", "classzisa_1_1DereferenceConstGridVariables" ],
      [ "DistributedArrayInfo", "structzisa_1_1DistributedArrayInfo.html", "structzisa_1_1DistributedArrayInfo" ],
      [ "DistributedCFLCondition", "classzisa_1_1DistributedCFLCondition.html", "classzisa_1_1DistributedCFLCondition" ],
      [ "DistributedGrid", "structzisa_1_1DistributedGrid.html", "structzisa_1_1DistributedGrid" ],
      [ "DistributedReferenceSolution", "classzisa_1_1DistributedReferenceSolution.html", "classzisa_1_1DistributedReferenceSolution" ],
      [ "DumpSnapshot", "classzisa_1_1DumpSnapshot.html", "classzisa_1_1DumpSnapshot" ],
      [ "Edge", "classzisa_1_1Edge.html", "classzisa_1_1Edge" ],
      [ "EdgeRange", "classzisa_1_1EdgeRange.html", "classzisa_1_1EdgeRange" ],
      [ "EdgeRule", "classzisa_1_1EdgeRule.html", "classzisa_1_1EdgeRule" ],
      [ "EnthalpyEntropy", "structzisa_1_1EnthalpyEntropy.html", "structzisa_1_1EnthalpyEntropy" ],
      [ "EquationOfState", "classzisa_1_1EquationOfState.html", "classzisa_1_1EquationOfState" ],
      [ "EquilibriumFluxBC", "classzisa_1_1EquilibriumFluxBC.html", "classzisa_1_1EquilibriumFluxBC" ],
      [ "Euler", "classzisa_1_1Euler.html", "classzisa_1_1Euler" ],
      [ "euler_full_xvars_t", "structzisa_1_1euler__full__xvars__t.html", "structzisa_1_1euler__full__xvars__t" ],
      [ "euler_like", "classzisa_1_1euler__like.html", null ],
      [ "euler_like< Euler >", "classzisa_1_1euler__like_3_01Euler_01_4.html", null ],
      [ "euler_var_t", "structzisa_1_1euler__var__t.html", "structzisa_1_1euler__var__t" ],
      [ "euler_xvar_t", "structzisa_1_1euler__xvar__t.html", "structzisa_1_1euler__xvar__t" ],
      [ "EulerExperiment", "classzisa_1_1EulerExperiment.html", "classzisa_1_1EulerExperiment" ],
      [ "EulerGlobalReconstruction", "classzisa_1_1EulerGlobalReconstruction.html", "classzisa_1_1EulerGlobalReconstruction" ],
      [ "EulerPlots", "classzisa_1_1EulerPlots.html", "classzisa_1_1EulerPlots" ],
      [ "EulerReferenceSolution", "classzisa_1_1EulerReferenceSolution.html", "classzisa_1_1EulerReferenceSolution" ],
      [ "EulerScaling", "classzisa_1_1EulerScaling.html", "classzisa_1_1EulerScaling" ],
      [ "Face", "classzisa_1_1Face.html", "classzisa_1_1Face" ],
      [ "FaceRange", "classzisa_1_1FaceRange.html", "classzisa_1_1FaceRange" ],
      [ "FastHelmholtzEOS", "classzisa_1_1FastHelmholtzEOS.html", "classzisa_1_1FastHelmholtzEOS" ],
      [ "Fehlberg", "classzisa_1_1Fehlberg.html", "classzisa_1_1Fehlberg" ],
      [ "FewPointsCache", "classzisa_1_1FewPointsCache.html", "classzisa_1_1FewPointsCache" ],
      [ "FileNameGenerator", "classzisa_1_1FileNameGenerator.html", "classzisa_1_1FileNameGenerator" ],
      [ "FixedFileNameGenerator", "classzisa_1_1FixedFileNameGenerator.html", "classzisa_1_1FixedFileNameGenerator" ],
      [ "FluxBC", "classzisa_1_1FluxBC.html", "classzisa_1_1FluxBC" ],
      [ "FluxLoop", "classzisa_1_1FluxLoop.html", "classzisa_1_1FluxLoop" ],
      [ "FNG", "classzisa_1_1FNG.html", "classzisa_1_1FNG" ],
      [ "ForwardEuler", "classzisa_1_1ForwardEuler.html", "classzisa_1_1ForwardEuler" ],
      [ "FourierNewton", "classzisa_1_1FourierNewton.html", "classzisa_1_1FourierNewton" ],
      [ "FourierSeries", "classzisa_1_1FourierSeries.html", "classzisa_1_1FourierSeries" ],
      [ "FourierSeriesBase", "classzisa_1_1FourierSeriesBase.html", "classzisa_1_1FourierSeriesBase" ],
      [ "FourierSeriesDerivative", "classzisa_1_1FourierSeriesDerivative.html", "classzisa_1_1FourierSeriesDerivative" ],
      [ "FrozenBC", "classzisa_1_1FrozenBC.html", "classzisa_1_1FrozenBC" ],
      [ "FullSphere", "classzisa_1_1FullSphere.html", "classzisa_1_1FullSphere" ],
      [ "GatheredVisInfo", "structzisa_1_1GatheredVisInfo.html", "structzisa_1_1GatheredVisInfo" ],
      [ "GatheredVisualization", "classzisa_1_1GatheredVisualization.html", "classzisa_1_1GatheredVisualization" ],
      [ "GaussLegendre", "structzisa_1_1GaussLegendre.html", "structzisa_1_1GaussLegendre" ],
      [ "GeneralPolytropeIC", "classzisa_1_1GeneralPolytropeIC.html", "classzisa_1_1GeneralPolytropeIC" ],
      [ "GlobalReconstruction", "classzisa_1_1GlobalReconstruction.html", "classzisa_1_1GlobalReconstruction" ],
      [ "GMSHElementInfo", "structzisa_1_1GMSHElementInfo.html", null ],
      [ "Gravity", "classzisa_1_1Gravity.html", "classzisa_1_1Gravity" ],
      [ "GravitySourceLoop", "classzisa_1_1GravitySourceLoop.html", "classzisa_1_1GravitySourceLoop" ],
      [ "GravitySourceLoop< NoEquilibrium, RC, EOS, Gravity, Scaling >", "classzisa_1_1GravitySourceLoop_3_01NoEquilibrium_00_01RC_00_01EOS_00_01Gravity_00_01Scaling_01_4.html", "classzisa_1_1GravitySourceLoop_3_01NoEquilibrium_00_01RC_00_01EOS_00_01Gravity_00_01Scaling_01_4" ],
      [ "Grid", "structzisa_1_1Grid.html", "structzisa_1_1Grid" ],
      [ "GridVariables", "classzisa_1_1GridVariables.html", "classzisa_1_1GridVariables" ],
      [ "HalfRadii", "classzisa_1_1HalfRadii.html", "classzisa_1_1HalfRadii" ],
      [ "Halo", "structzisa_1_1Halo.html", "structzisa_1_1Halo" ],
      [ "HaloExchange", "classzisa_1_1HaloExchange.html", "classzisa_1_1HaloExchange" ],
      [ "HaloExchangeBC", "classzisa_1_1HaloExchangeBC.html", "classzisa_1_1HaloExchangeBC" ],
      [ "HaloReceiveInfo", "structzisa_1_1HaloReceiveInfo.html", "structzisa_1_1HaloReceiveInfo" ],
      [ "HaloReceivePart", "classzisa_1_1HaloReceivePart.html", "classzisa_1_1HaloReceivePart" ],
      [ "HaloRemoteInfo", "structzisa_1_1HaloRemoteInfo.html", "structzisa_1_1HaloRemoteInfo" ],
      [ "HaloSendInfo", "structzisa_1_1HaloSendInfo.html", "structzisa_1_1HaloSendInfo" ],
      [ "HaloSendPart", "classzisa_1_1HaloSendPart.html", "classzisa_1_1HaloSendPart" ],
      [ "HDF5ParallelWriter", "classzisa_1_1HDF5ParallelWriter.html", "classzisa_1_1HDF5ParallelWriter" ],
      [ "HDF5UnstructuredFileDimensions", "structzisa_1_1HDF5UnstructuredFileDimensions.html", "structzisa_1_1HDF5UnstructuredFileDimensions" ],
      [ "HDF5UnstructuredReader", "classzisa_1_1HDF5UnstructuredReader.html", "classzisa_1_1HDF5UnstructuredReader" ],
      [ "HDF5UnstructuredWriter", "classzisa_1_1HDF5UnstructuredWriter.html", "classzisa_1_1HDF5UnstructuredWriter" ],
      [ "Heating", "classzisa_1_1Heating.html", "classzisa_1_1Heating" ],
      [ "HelmholtzEOS", "classzisa_1_1HelmholtzEOS.html", "classzisa_1_1HelmholtzEOS" ],
      [ "hllc_speeds", "classzisa_1_1hllc__speeds.html", null ],
      [ "hllc_speeds< IdealGasEOS >", "classzisa_1_1hllc__speeds_3_01IdealGasEOS_01_4.html", null ],
      [ "HLLCBatten", "classzisa_1_1HLLCBatten.html", "classzisa_1_1HLLCBatten" ],
      [ "HybridWENO", "classzisa_1_1HybridWENO.html", "classzisa_1_1HybridWENO" ],
      [ "HybridWENOParams", "structzisa_1_1HybridWENOParams.html", "structzisa_1_1HybridWENOParams" ],
      [ "IdealGasEOS", "classzisa_1_1IdealGasEOS.html", "classzisa_1_1IdealGasEOS" ],
      [ "InputParameters", "classzisa_1_1InputParameters.html", "classzisa_1_1InputParameters" ],
      [ "InstantaneousPhysics", "classzisa_1_1InstantaneousPhysics.html", "classzisa_1_1InstantaneousPhysics" ],
      [ "integer_tree_traits", "structzisa_1_1integer__tree__traits.html", null ],
      [ "InvalidNumericalExperiment", "classzisa_1_1InvalidNumericalExperiment.html", "classzisa_1_1InvalidNumericalExperiment" ],
      [ "IsentropicEquilibrium", "structzisa_1_1IsentropicEquilibrium.html", "structzisa_1_1IsentropicEquilibrium" ],
      [ "IsentropicEquilibriumValuesTraits", "structzisa_1_1IsentropicEquilibriumValuesTraits.html", null ],
      [ "IsentropicEquilibriumValuesTraits< IdealGasEOS >", "structzisa_1_1IsentropicEquilibriumValuesTraits_3_01IdealGasEOS_01_4.html", "structzisa_1_1IsentropicEquilibriumValuesTraits_3_01IdealGasEOS_01_4" ],
      [ "JankaEOS", "classzisa_1_1JankaEOS.html", "classzisa_1_1JankaEOS" ],
      [ "JankaEOSParams", "structzisa_1_1JankaEOSParams.html", "structzisa_1_1JankaEOSParams" ],
      [ "LABColor", "structzisa_1_1LABColor.html", "structzisa_1_1LABColor" ],
      [ "LoadSnapshot", "classzisa_1_1LoadSnapshot.html", "classzisa_1_1LoadSnapshot" ],
      [ "LocalCFL", "classzisa_1_1LocalCFL.html", "classzisa_1_1LocalCFL" ],
      [ "LocalEOSState", "classzisa_1_1LocalEOSState.html", null ],
      [ "LocalEOSState< IdealGasEOS >", "classzisa_1_1LocalEOSState_3_01IdealGasEOS_01_4.html", "classzisa_1_1LocalEOSState_3_01IdealGasEOS_01_4" ],
      [ "LocalEquilibrium", "classzisa_1_1LocalEquilibrium.html", "classzisa_1_1LocalEquilibrium" ],
      [ "LocalEquilibrium< NoEquilibrium >", "classzisa_1_1LocalEquilibrium_3_01NoEquilibrium_01_4.html", "classzisa_1_1LocalEquilibrium_3_01NoEquilibrium_01_4" ],
      [ "LocalEquilibriumBase", "classzisa_1_1LocalEquilibriumBase.html", "classzisa_1_1LocalEquilibriumBase" ],
      [ "LocalEulerScaling", "classzisa_1_1LocalEulerScaling.html", "classzisa_1_1LocalEulerScaling" ],
      [ "LocalRCParams", "structzisa_1_1LocalRCParams.html", "structzisa_1_1LocalRCParams" ],
      [ "LocalReconstruction", "classzisa_1_1LocalReconstruction.html", "classzisa_1_1LocalReconstruction" ],
      [ "LocalUnityScaling", "classzisa_1_1LocalUnityScaling.html", "classzisa_1_1LocalUnityScaling" ],
      [ "LSQSolver", "classzisa_1_1LSQSolver.html", "classzisa_1_1LSQSolver" ],
      [ "LSQSolverFamily", "classzisa_1_1LSQSolverFamily.html", "classzisa_1_1LSQSolverFamily" ],
      [ "Momentum", "structzisa_1_1Momentum.html", null ],
      [ "MPIAllReduce", "classzisa_1_1MPIAllReduce.html", "classzisa_1_1MPIAllReduce" ],
      [ "MPIHaloExchange", "classzisa_1_1MPIHaloExchange.html", "classzisa_1_1MPIHaloExchange" ],
      [ "MPINumericalExperiment", "classzisa_1_1MPINumericalExperiment.html", "classzisa_1_1MPINumericalExperiment" ],
      [ "MPIProgressBar", "classzisa_1_1MPIProgressBar.html", "classzisa_1_1MPIProgressBar" ],
      [ "MPISingleNodeArrayGatherer", "classzisa_1_1MPISingleNodeArrayGatherer.html", "classzisa_1_1MPISingleNodeArrayGatherer" ],
      [ "MPISingleNodeArrayGathererFactory", "classzisa_1_1MPISingleNodeArrayGathererFactory.html", "classzisa_1_1MPISingleNodeArrayGathererFactory" ],
      [ "MPISingleNodeArrayScatterer", "classzisa_1_1MPISingleNodeArrayScatterer.html", "classzisa_1_1MPISingleNodeArrayScatterer" ],
      [ "MPISingleNodeArrayScattererFactory", "classzisa_1_1MPISingleNodeArrayScattererFactory.html", "classzisa_1_1MPISingleNodeArrayScattererFactory" ],
      [ "NoBoundaryCondition", "classzisa_1_1NoBoundaryCondition.html", "classzisa_1_1NoBoundaryCondition" ],
      [ "NoDereference", "classzisa_1_1NoDereference.html", null ],
      [ "NoEquilibrium", "structzisa_1_1NoEquilibrium.html", "structzisa_1_1NoEquilibrium" ],
      [ "NoFluxBC", "classzisa_1_1NoFluxBC.html", "classzisa_1_1NoFluxBC" ],
      [ "NoGravity", "classzisa_1_1NoGravity.html", "classzisa_1_1NoGravity" ],
      [ "NoHaloExchange", "classzisa_1_1NoHaloExchange.html", "classzisa_1_1NoHaloExchange" ],
      [ "NoInstantaneousPhysics", "classzisa_1_1NoInstantaneousPhysics.html", "classzisa_1_1NoInstantaneousPhysics" ],
      [ "NonUniformLinearInterpolation", "classzisa_1_1NonUniformLinearInterpolation.html", "classzisa_1_1NonUniformLinearInterpolation" ],
      [ "NoSanityCheck", "classzisa_1_1NoSanityCheck.html", "classzisa_1_1NoSanityCheck" ],
      [ "NoVisualization", "classzisa_1_1NoVisualization.html", "classzisa_1_1NoVisualization" ],
      [ "NumericalExperiment", "classzisa_1_1NumericalExperiment.html", "classzisa_1_1NumericalExperiment" ],
      [ "NumericalExperimentFactory", "classzisa_1_1NumericalExperimentFactory.html", "classzisa_1_1NumericalExperimentFactory" ],
      [ "omp_policy", "structzisa_1_1omp__policy.html", null ],
      [ "ParallelDumpSnapshot", "classzisa_1_1ParallelDumpSnapshot.html", "classzisa_1_1ParallelDumpSnapshot" ],
      [ "ParallelLoadSnapshot", "classzisa_1_1ParallelLoadSnapshot.html", "classzisa_1_1ParallelLoadSnapshot" ],
      [ "PartitionedGrid", "structzisa_1_1PartitionedGrid.html", "structzisa_1_1PartitionedGrid" ],
      [ "Permutation", "structzisa_1_1Permutation.html", "structzisa_1_1Permutation" ],
      [ "PlainIndexRange", "classzisa_1_1PlainIndexRange.html", "classzisa_1_1PlainIndexRange" ],
      [ "PlottingStepsParameters", "structzisa_1_1PlottingStepsParameters.html", "structzisa_1_1PlottingStepsParameters" ],
      [ "PointLocator", "classzisa_1_1PointLocator.html", "classzisa_1_1PointLocator" ],
      [ "PointMassGravity", "classzisa_1_1PointMassGravity.html", "classzisa_1_1PointMassGravity" ],
      [ "PointMassGravityAxial", "classzisa_1_1PointMassGravityAxial.html", "classzisa_1_1PointMassGravityAxial" ],
      [ "PointMassGravityRadial", "classzisa_1_1PointMassGravityRadial.html", "classzisa_1_1PointMassGravityRadial" ],
      [ "PointMassGravityXAligned", "classzisa_1_1PointMassGravityXAligned.html", "classzisa_1_1PointMassGravityXAligned" ],
      [ "PointMassGravityYAligned", "classzisa_1_1PointMassGravityYAligned.html", "classzisa_1_1PointMassGravityYAligned" ],
      [ "PointwiseScale", "classzisa_1_1PointwiseScale.html", "classzisa_1_1PointwiseScale" ],
      [ "PointwiseSubtract", "classzisa_1_1PointwiseSubtract.html", "classzisa_1_1PointwiseSubtract" ],
      [ "PointwiseSum", "classzisa_1_1PointwiseSum.html", "classzisa_1_1PointwiseSum" ],
      [ "PoissonSolver", "classzisa_1_1PoissonSolver.html", "classzisa_1_1PoissonSolver" ],
      [ "PolyIndexRange", "classzisa_1_1PolyIndexRange.html", null ],
      [ "PolyIndexRange< 2 >", "classzisa_1_1PolyIndexRange_3_012_01_4.html", "classzisa_1_1PolyIndexRange_3_012_01_4" ],
      [ "PolyIndexRange< 3 >", "classzisa_1_1PolyIndexRange_3_013_01_4.html", "classzisa_1_1PolyIndexRange_3_013_01_4" ],
      [ "PolyND", "classzisa_1_1PolyND.html", "classzisa_1_1PolyND" ],
      [ "PolynomialCRTP", "classzisa_1_1PolynomialCRTP.html", null ],
      [ "Polytrope", "classzisa_1_1Polytrope.html", "classzisa_1_1Polytrope" ],
      [ "PolytropeGravity", "classzisa_1_1PolytropeGravity.html", "classzisa_1_1PolytropeGravity" ],
      [ "PolytropeGravityRadial", "classzisa_1_1PolytropeGravityRadial.html", "classzisa_1_1PolytropeGravityRadial" ],
      [ "PolytropeGravityWithJump", "classzisa_1_1PolytropeGravityWithJump.html", "classzisa_1_1PolytropeGravityWithJump" ],
      [ "PolytropeGravityWithJumpRadial", "classzisa_1_1PolytropeGravityWithJumpRadial.html", "classzisa_1_1PolytropeGravityWithJumpRadial" ],
      [ "PolytropeIC", "classzisa_1_1PolytropeIC.html", "classzisa_1_1PolytropeIC" ],
      [ "PolytropeParams", "structzisa_1_1PolytropeParams.html", "structzisa_1_1PolytropeParams" ],
      [ "PolytropeWithJumpIC", "classzisa_1_1PolytropeWithJumpIC.html", "classzisa_1_1PolytropeWithJumpIC" ],
      [ "PressureEntropy", "structzisa_1_1PressureEntropy.html", "structzisa_1_1PressureEntropy" ],
      [ "ProgressBar", "classzisa_1_1ProgressBar.html", "classzisa_1_1ProgressBar" ],
      [ "QRDegrees", "structzisa_1_1QRDegrees.html", "structzisa_1_1QRDegrees" ],
      [ "RadialAlignment", "classzisa_1_1RadialAlignment.html", "classzisa_1_1RadialAlignment" ],
      [ "RadialGravity", "classzisa_1_1RadialGravity.html", "classzisa_1_1RadialGravity" ],
      [ "RadialPoissonSolver", "classzisa_1_1RadialPoissonSolver.html", "classzisa_1_1RadialPoissonSolver" ],
      [ "Range", "classzisa_1_1Range.html", "classzisa_1_1Range" ],
      [ "range_traits", "structzisa_1_1range__traits.html", "structzisa_1_1range__traits" ],
      [ "RateOfChange", "classzisa_1_1RateOfChange.html", "classzisa_1_1RateOfChange" ],
      [ "RayleighTaylor", "classzisa_1_1RayleighTaylor.html", "classzisa_1_1RayleighTaylor" ],
      [ "ReferenceSolution", "classzisa_1_1ReferenceSolution.html", "classzisa_1_1ReferenceSolution" ],
      [ "Region", "classzisa_1_1Region.html", "classzisa_1_1Region" ],
      [ "RejectLargeDensityChange", "classzisa_1_1RejectLargeDensityChange.html", "classzisa_1_1RejectLargeDensityChange" ],
      [ "RejectNothing", "classzisa_1_1RejectNothing.html", "classzisa_1_1RejectNothing" ],
      [ "RGBColor", "structzisa_1_1RGBColor.html", "structzisa_1_1RGBColor" ],
      [ "RhoE", "structzisa_1_1RhoE.html", "structzisa_1_1RhoE" ],
      [ "RhoEntropy", "structzisa_1_1RhoEntropy.html", "structzisa_1_1RhoEntropy" ],
      [ "RhoP", "structzisa_1_1RhoP.html", "structzisa_1_1RhoP" ],
      [ "RhoT", "structzisa_1_1RhoT.html", "structzisa_1_1RhoT" ],
      [ "RK4", "classzisa_1_1RK4.html", "classzisa_1_1RK4" ],
      [ "RoeAverage", "classzisa_1_1RoeAverage.html", "classzisa_1_1RoeAverage" ],
      [ "RollingConvergenceRate", "classzisa_1_1RollingConvergenceRate.html", "classzisa_1_1RollingConvergenceRate" ],
      [ "RungeKutta", "classzisa_1_1RungeKutta.html", "classzisa_1_1RungeKutta" ],
      [ "SanityCheck", "classzisa_1_1SanityCheck.html", "classzisa_1_1SanityCheck" ],
      [ "SanityCheckFor", "classzisa_1_1SanityCheckFor.html", "classzisa_1_1SanityCheckFor" ],
      [ "ScalarPlot", "classzisa_1_1ScalarPlot.html", "classzisa_1_1ScalarPlot" ],
      [ "ScatteredDataSource", "classzisa_1_1ScatteredDataSource.html", "classzisa_1_1ScatteredDataSource" ],
      [ "SelfGravity", "classzisa_1_1SelfGravity.html", "classzisa_1_1SelfGravity" ],
      [ "serial_policy", "structzisa_1_1serial__policy.html", null ],
      [ "SerialDumpSnapshot", "classzisa_1_1SerialDumpSnapshot.html", "classzisa_1_1SerialDumpSnapshot" ],
      [ "SerialLoadSnapshot", "classzisa_1_1SerialLoadSnapshot.html", "classzisa_1_1SerialLoadSnapshot" ],
      [ "SerialProgressBar", "classzisa_1_1SerialProgressBar.html", "classzisa_1_1SerialProgressBar" ],
      [ "SingleFileNameGenerator", "classzisa_1_1SingleFileNameGenerator.html", "classzisa_1_1SingleFileNameGenerator" ],
      [ "SmoothBubble", "classzisa_1_1SmoothBubble.html", "classzisa_1_1SmoothBubble" ],
      [ "Sphere", "structzisa_1_1Sphere.html", "structzisa_1_1Sphere" ],
      [ "SphericalGravity", "classzisa_1_1SphericalGravity.html", "classzisa_1_1SphericalGravity" ],
      [ "SphericalShell", "structzisa_1_1SphericalShell.html", "structzisa_1_1SphericalShell" ],
      [ "SRGBColor", "structzisa_1_1SRGBColor.html", "structzisa_1_1SRGBColor" ],
      [ "SSP2", "classzisa_1_1SSP2.html", "classzisa_1_1SSP2" ],
      [ "SSP3", "classzisa_1_1SSP3.html", "classzisa_1_1SSP3" ],
      [ "StaticRungeKutta", "classzisa_1_1StaticRungeKutta.html", "classzisa_1_1StaticRungeKutta" ],
      [ "StellarConvection", "classzisa_1_1StellarConvection.html", "classzisa_1_1StellarConvection" ],
      [ "Stencil", "classzisa_1_1Stencil.html", "classzisa_1_1Stencil" ],
      [ "stencil_family_dispatch_tag", "structzisa_1_1stencil__family__dispatch__tag.html", null ],
      [ "StencilBasedIndicator", "classzisa_1_1StencilBasedIndicator.html", "classzisa_1_1StencilBasedIndicator" ],
      [ "StencilFamily", "classzisa_1_1StencilFamily.html", "classzisa_1_1StencilFamily" ],
      [ "StencilFamilyParams", "structzisa_1_1StencilFamilyParams.html", "structzisa_1_1StencilFamilyParams" ],
      [ "StencilParams", "structzisa_1_1StencilParams.html", "structzisa_1_1StencilParams" ],
      [ "StepRejection", "classzisa_1_1StepRejection.html", "classzisa_1_1StepRejection" ],
      [ "StrictSymmetricChoices", "classzisa_1_1StrictSymmetricChoices.html", "classzisa_1_1StrictSymmetricChoices" ],
      [ "SumRatesOfChange", "classzisa_1_1SumRatesOfChange.html", "classzisa_1_1SumRatesOfChange" ],
      [ "TendencyBuffers", "classzisa_1_1TendencyBuffers.html", "classzisa_1_1TendencyBuffers" ],
      [ "TetrahedralCone", "classzisa_1_1TetrahedralCone.html", "classzisa_1_1TetrahedralCone" ],
      [ "TetrahedralRule", "structzisa_1_1TetrahedralRule.html", "structzisa_1_1TetrahedralRule" ],
      [ "Tetrahedron", "classzisa_1_1Tetrahedron.html", "classzisa_1_1Tetrahedron" ],
      [ "TimeIntegration", "classzisa_1_1TimeIntegration.html", "classzisa_1_1TimeIntegration" ],
      [ "TimeKeeperParameters", "structzisa_1_1TimeKeeperParameters.html", "structzisa_1_1TimeKeeperParameters" ],
      [ "TimeLoop", "classzisa_1_1TimeLoop.html", "classzisa_1_1TimeLoop" ],
      [ "Tree", "classzisa_1_1Tree.html", "classzisa_1_1Tree" ],
      [ "tree_traits", "structzisa_1_1tree__traits.html", null ],
      [ "Triangle", "classzisa_1_1Triangle.html", "classzisa_1_1Triangle" ],
      [ "TriangleRange", "classzisa_1_1TriangleRange.html", "classzisa_1_1TriangleRange" ],
      [ "TriangularCone", "classzisa_1_1TriangularCone.html", "classzisa_1_1TriangularCone" ],
      [ "TriangularRule", "structzisa_1_1TriangularRule.html", "structzisa_1_1TriangularRule" ],
      [ "TriPlot", "classzisa_1_1TriPlot.html", "classzisa_1_1TriPlot" ],
      [ "TypicalNumericalExperiment", "classzisa_1_1TypicalNumericalExperiment.html", "classzisa_1_1TypicalNumericalExperiment" ],
      [ "UnionOfRegions", "classzisa_1_1UnionOfRegions.html", "classzisa_1_1UnionOfRegions" ],
      [ "UnityScaling", "classzisa_1_1UnityScaling.html", "classzisa_1_1UnityScaling" ],
      [ "Visualization", "classzisa_1_1Visualization.html", "classzisa_1_1Visualization" ],
      [ "WENO_AO", "classzisa_1_1WENO__AO.html", "classzisa_1_1WENO__AO" ],
      [ "Wicker", "classzisa_1_1Wicker.html", "classzisa_1_1Wicker" ],
      [ "XYZ", "classzisa_1_1XYZ.html", "classzisa_1_1XYZ" ],
      [ "XYZColor", "structzisa_1_1XYZColor.html", "structzisa_1_1XYZColor" ],
      [ "ZeroRateOfChange", "classzisa_1_1ZeroRateOfChange.html", "classzisa_1_1ZeroRateOfChange" ]
    ] ]
];