//
// Created by lucg on 24/01/2020.
//

#ifndef ZISA_MPI_TAG_CONSTANTS_HPP
#define ZISA_MPI_TAG_CONSTANTS_HPP

#define ZISA_MPI_TAG_ALL_VARS_VISUALIZATION 234 // needs 2 successive IDs
#define ZISA_MPI_TAG_ALL_VARS_POSTPROCESS 823   // needs 2 successive IDs

#define ZISA_MPI_TAG_DOMAIN_DECOMPOSITION_ALL_VARS 917 // needs 2 successive IDs

#define ZISA_MPI_TAG_HALO_EXCHANGE_CVARS 1000
#define ZISA_MPI_TAG_EXCHANGE_HALO_INFO_XFER 1234

#define ZISA_MPI_TAG_REFERENCE_XFER 2000 // needs 3 successive IDs.
#define ZISA_MPI_TAG_REFERENCE_ORG 2200

#endif // ZISA_MPI_TAG_CONSTANTS_HPP
