// SPDX-License-Identifier: MIT
// Copyright (c) 2021 ETH Zurich, Luc Grosheintz-Laval

//
// Created by lucg on 24/01/2020.
//

#ifndef ZISA_MPI_TAG_CONSTANTS_HPP
#define ZISA_MPI_TAG_CONSTANTS_HPP

#define ZISA_MPI_TAG_ALL_VARS_VISUALIZATION 234 // needs 2 successive IDs
#define ZISA_MPI_TAG_ALL_VARS_POSTPROCESS 823   // needs 2 successive IDs

#define ZISA_MPI_TAG_DOMAIN_DECOMPOSITION_ALL_VARS 917 // needs 2 successive IDs

#define ZISA_MPI_TAG_HALO_EXCHANGE_CVARS 1000
#define ZISA_MPI_TAG_HALO_EXCHANGE_AVARS 1001
#define ZISA_MPI_TAG_EXCHANGE_HALO_INFO_XFER 1234

#define ZISA_MPI_TAG_REFERENCE_XFER 2000 // needs 3 successive IDs.
#define ZISA_MPI_TAG_REFERENCE_ORG 2200

#define ZISA_MPI_TAG_LOAD_ALL_VARS 2900
#define ZISA_MPI_TAG_GATHERED_VIS 3000
#define ZISA_MPI_TAG_SCATTERED_VIS 10000

#endif // ZISA_MPI_TAG_CONSTANTS_HPP
